### PR TITLE
moving trtis to 19.08 in BERT

### PR DESCRIPTION
**Pull request by swethmandava**

### CODE REVIEW

**Comment by lapolonio** [comment]
i had to make these changes to get the docker/build to work

```
diff --git a/TensorFlow/LanguageModeling/BERT/Dockerfile b/TensorFlow/LanguageModeling/BERT/Dockerfile
index a56ef26..552d709 100644
--- a/TensorFlow/LanguageModeling/BERT/Dockerfile
+++ b/TensorFlow/LanguageModeling/BERT/Dockerfile
@@ -17,10 +17,10 @@ RUN git clone https://github.com/titipata/pubmed_parser
 RUN pip3 install /workspace/pubmed_parser

 #Copy the perf_client over
-COPY --from=trt /workspace/install/ /workspace/install/
+COPY --from=trt /workspace/build/dist/dist/ /workspace/install/

 #Install the python wheel with pip
-RUN pip install /workspace/install/python/tensorrtserver*.whl
+RUN pip install /workspace/install/tensorrtserver*.whl

 WORKDIR /workspace/bert
 COPY . .
```

**Comment by lapolonio** [comment]
also need to add `apt-get install libcurl3` to bert container

**Comment by lapolonio** [comment]
also is there a reason not to use 19.09 or 19.10? I'm interested in using TensorRT 6.

**Comment by swethmandava** [comment]
you might be using an older submodule, please update tensorrt-inference-server to use branch r19.08
No, please go ahead and use the latest containers. 19.08 was the latest container at the time of publishing.

**Pull request merged**
