### PR TITLE
Update extract_RN50_weights.py

### PR DESCRIPTION
**Pull request by amrragab8080**
removing contrib - not compatible with TF2.0.

You might need to maintain two scripts for TF1.x compatibility but contrib was removed in TF2.0

### CODE REVIEW

**Comment by pribalta** [comment]
@amrragab8080 we're working on making MRCNN fully TF2 compliant. Stay tuned!

**Comment by amrragab8080** [comment]
@pribalta I suppose but for now the code and the TF2 MaskRCNN pipeline does not function. You will get this error when preparing the dataset:
```
Traceback (most recent call last):
  File "extract_RN50_weights.py", line 120, in <module>
    main(sys.argv[1:])
  File "extract_RN50_weights.py", line 112, in main
    rename(checkpoint_dir, save_to, dry_run, verbose)
  File "extract_RN50_weights.py", line 47, in rename
    for var_name, _ in tf.contrib.framework.list_variables(checkpoint_dir):
AttributeError: module 'tensorflow' has no attribute 'contrib'
```

**Comment by subhankar-ghosh** [comment]
@amrragab8080  This PR will work only for TF2 but will break things for TF1. Since this is a common codebase for both TF1 and TF2 I would suggest the following changes instead:

`from distutils.version import LooseVersion
...
        if LooseVersion(tf.__version__) < LooseVersion("2.0.0"):
            file_list = tf.contrib.framework.list_variables(checkpoint_dir)
        else:
            file_list = tf.train.list_variables(checkpoint_dir)

        for var_name, _ in file_list:
`
Can you try this?

**Comment by amrragab8080** [comment]
Yep that works - I saw you had a separate directory for TF1 - MaskRCNN and saw that just points the TF2.
https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/Segmentation/MaskRCNN/README.md

So your update is better. Thanks

**Comment by subhankar-ghosh** [comment]
@amrragab8080 , sure can you change the PR so we can merge it. Thanks for pointing it out.

**Comment by amrragab8080** [comment]
@subhankar-ghosh I changed it on my fork but its not reflects - I think you need to reopen PR for the changes to reflect.

**Comment by subhankar-ghosh** [comment]
@amrragab8080 , it is reopened can you make the above changes? https://github.com/NVIDIA/DeepLearningExamples/pull/597#issuecomment-661538924

**Comment by subhankar-ghosh** [comment]
@szmigacz Can you merge this PR?

**Pull request merged**
